name: Deployment CI

on:
  push:
    branches: 
      - kustomize

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
